language: python

python:
  - "3.7"

# command to install dependencies
install:
  - pip install -r requirements.txt

# command to run tests
script: 
  - chmod +x demoapp/server.py
  - nohup python /path/to/test.py > output.log &
  - webdrivermanager firefox chrome --linkpath /usr/local/bin
  - robot login_tests
  - pkill -f demoapp/server.py
  - nohup python -u ./demoapp/server.py > output.log &