language: python

python:
  - "3.9"

addons:
  firefox: latest

# command to install dependencies
install:
  - pip install -r requirements.txt

# command to run tests
script: 
  # Allowing port 8080
  - sudo ufw allow 8080
  
  # Changing app permission to executable and running in background
  - chmod +x demoapp/server.py
  - nohup python demoapp/server.py > output.log &
  
  # Downloading GeckoDriver and moving it to /usr/loca/bin
  - wget -N https://github.com/mozilla/geckodriver/releases/download/v0.29.0/geckodriver-v0.29.0-linux64.tar.gz -P ~/
  - tar -xzf ~/geckodriver-v0.29.0-linux64.tar.gz -C ~/
  - rm ~/geckodriver-v0.29.0-linux64.tar.gz
  - sudo mv -f ~/geckodriver /usr/local/share
  - sudo chmod +x /usr/local/share/geckodriver
  - sudo ln -s /usr/local/share/geckodriver /usr/local/bin/geckodriver
  
  # Sleep for 30s for server to start up
  - sleep 30

  # Check port and address status
  - sudo ss -tulwn
  
  # perform tests
  - robot login_tests
  
  # Check port and address status
  - sudo ss -tulwn

  # Kill the process
  - pkill -f demoapp/server.py
  # - nohup python -u ./demoapp/server.py > output.log &