language: python

python:
  - "3.7"

# command to install dependencies
install:
  - pip install -r requirements.txt

# command to run tests
script: 
  - python demoapp/server.py
  - webdrivermanager firefox chrome --linkpath /usr/local/bin
  - robot login_tests