language: python

python:
  - "3.9"

addons:
  firefox: latest

# command to install dependencies
install:
  - pip install -r requirements.txt

# command to run tests
script: 
  - chmod +x demoapp/server.py
  - nohup python /path/to/test.py > output.log &
  - wget -N https://github.com/mozilla/geckodriver/releases/download/v0.29.0/geckodriver-v0.29.0-linux64.tar.gz -P ~/
  - tar -xzf ~/geckodriver-v0.29.0-linux64.tar.gz -C ~/
  - rm ~/geckodriver-v0.29.0-linux64.tar.gz
  - sudo mv -f ~/geckodriver /usr/local/share
  - sudo chmod +x /usr/local/share/geckodriver
  - sudo ln -s /usr/local/share/geckodriver /usr/local/bin/geckodriver
  - sudo ss -tulwn
  - robot login_tests
  - sudo ss -tulwn
  - pkill -f demoapp/server.py
  - nohup python -u ./demoapp/server.py > output.log &