language: python
python:
- '3.9'
addons:
  firefox: latest
install:
- pip install -r requirements.txt
script:
- sudo ufw allow 8080
- chmod +x demoapp/server.py
- nohup python demoapp/server.py > output.log &
- wget -N https://github.com/mozilla/geckodriver/releases/download/v0.29.0/geckodriver-v0.29.0-linux64.tar.gz
  -P ~/
- tar -xzf ~/geckodriver-v0.29.0-linux64.tar.gz -C ~/
- rm ~/geckodriver-v0.29.0-linux64.tar.gz
- sudo mv -f ~/geckodriver /usr/local/share
- sudo chmod +x /usr/local/share/geckodriver
- sudo ln -s /usr/local/share/geckodriver /usr/local/bin/geckodriver
- sudo ss -tulwn
- robot $test
- sudo ss -tulwn
- pkill -f demoapp/server.py
- echo $temp
env:
  global:
  - secure: lx7bLWD5AR2qOGrqolRbJWYXarf5rP9YrElFUcFVzxKhNWxMRAYnTtKALRQwkiY2X/Z9krFqCP16Udo7M47QuR1JnWxSptNK+8z133N4+txeUVxN1M5FZQEURFae4wMqbwdYYCgSBKv8aufXK+nrZ/XkPgJMtAhZj3paV+MVaB4QcN+o7Htm8tm+KjC7zhM+1mtrhfd6A1TCs1Bs4BQLXqU/HNUIwFnkHbqNRTXahsBSGgYehpSMQxlmvxOIClxF6DBZB4DJrh5EgbupudzEJmQ0KOx87TIOiWn3OWCYXvyaxn7uJ+T4g0OzQIWw003WnOOTnJK8KXdR7z5i4Zlpg+Cnna/Bu1aW+tzy4Nn//hCyLaC4ZgJ+P49Oq4eSPgkuiSTp41Hw2cDF0DwkFijGxUD2wugVJsO5S6h3/FLcrev69UqvD7HvZbmPBrK3CAhu/rTZep2HE2+UGYvUJhGK3bijggw6r8u7bP2jBrCTYU6D827LSMkJZZIx9lBPMhYZhzztQqzeXUXsEn6yqO51gj5XrVpRj62lElKgMHXKGf45UqtqztEQJ3exCnC3TL8n+ySd6M3eYqjP49xcfiI3XL2xAKHpwcR3z5Ofz5uONqqZwOTmw1Puxbms1GYtSEfSLjcDe+ilmuBEUQq4DgzNynO6E7+zsdujKW7IT2EM4F8=
  - secure: nez6Gjhgj4wrOMDohPMpH0/2voNLho4FDRi12WYO0rHB1qESZgeuPCi/VZNi3L4VVpJ4s++xEwQM0RdWOzWWQbWzHF8pm1fLdjw0WL/R7PK7KEcenRR30MG9AcXiF5iZOknYatK4bRLvnFzN+55hkWzGWSGg7tMQi5/UpdVyR5nWy+JKRNDqRB7M0Kcj6Cs51qpnFNk01FhiTuLf3SAQPhdWNZ+pnnBTg1xri27chL+Q047H/MHp0n3gvzZIzAIwvHqyZEGJchkjRjS/SqcJBgaVAL6nnYXyz8eHaJ5M0UjdKBNt+M7oSdriZYOEdLOWXqrtLL8iaTlPQadakXJE698aW6fbGYdGMCn0He0eXSBcM51p+3Pq1R11EgaM7WenFMZJPNGpIDwKJvX6SomlEC7uxlp0ZXjm6dN0wu7/1du8yx//oEXFdSgjO6Ou+M4E83/HCAWXyy/HW6vet0IxBbTOyUndWMZidfIfMHTu/fpg1w4Y99WjjDKELPwl5qtRuU39ysGtrvmh5iYq10VnmJ+WYz75Dni3Eyfli1NJiOqoC28g+axUU5RtV9Y3u6POyyVhZNiLTX2HugeZESpKoOQEPYoms0shW9JFzFiqqpD/cGmYLXOyNpHIxpF+bZMGFtc823PsvryQUzgUZFx9BDkDrh5uqJz/sOl4gFgfSFE=
  - secure: ZBNsizrAy6MDi6gqqwL3Zo3UvYiuQeDg3EQgDcMiOp0pnLvBbmpdl2ZcZ77er8d/sCuGgANsytnWRLQBXRsaTltPnutazDphiG+vfslCdWWir7mYasMUNT/RidUldOKaL0p3W9Dp8yhUFjel2TxMGR/oVVyCQDcGNvGO+pJaEwAymNj2jnJt8Hb5wouBhMpQcBsFTpl64NG3hvTA1D9oVjyhsQnOGgOZ72tHDsqgJETJwUdrjqcqqVdAaJRNNvBTTSrgKz5rmXh/8PitTcbxteDdBazpJgn6Mb0ArjK7vlC8XHEngAjg8LJcp732p36bVVh7YZvzvcc8KecahmTl3ejsG/ORJE56idzv0kLpbhddaK+bUicTeC6xJLqn82w46fwlR8SQR6vZwb2O1iL0WS4XX4X2Tlx0EIGXpXARurG6qKShGOcrblXxfAmPAyxD9tQqBtdrw4R5QO6jq35l/NY7rU/tvQg6VraGnmQzSfX64CMsgk36lfDTyvfIpyMXzcT5EN6Ocz/S2zuD79nOz+YzvUOHBtPjWj8QUlw8ycU+0odCn5twrsPDmaG0YBXja0sUbYzyZzHg84sf2eylyU6kuq2GFxGmXEPSwU5gkyYEkrUrVbsIEnrkadyxA/ADw6f3FUNqgDBx545pBLfflFkrD/fC2DwJy31ZCYIBDcI=
  - secure: f7h9wMunJtkSWfO/sY0drfNQ3ZI5WyGRDfhMUN6ZLVmNGxg17nFxqR+P7rfYRWJzSrC0Q2ks/pugpCgSwvX2gf/lVj2CyVsazyg+oE/4rRBnx5bHwD9oQxcs2FOCMlsl6WQHof2F+JxHHTeHbH/Hc+xa6mF2F7SfG8KbAtlU7HGOgPr799cllcuygEkLmNUNBCgoJ23FOJCwMor/q0+Jzl0/MEphnW9D9LhONdahgg92wWix7heuO+GWkNZctDTSTM8mZfPkz/ERjuFgZ2O5Zu5nX/BLYWJjxe1bO8EkhLSzpsW2vLiLwizKAqdxS0cxoFPiIUDmWatlu62E/7Fc4roospVpMuEfM++qu2hQ8SkQuGGx4M3jb917T/0DbaQPWSmpFzP5ywbQyJnzqbn/z1+DiPpTs+zm8fFJ1cL40cjMj4IJvwGAcc89O6Ubgqadar/DjPi+lxY6ZdVsilKzltAhsF+01FRPNdJpDZ5hHex01r7j5sl6PRjOl3HV9nLTgSIo0UQE6Tpl9A0cjX3sTqoyddSwIL5dq9uADVuD8qjYDDeLhrb+PWE2/QOr6CKD3qtUsd+W5BUeAU1ijy+xyN/7fmEFXO/YN2e+OGYPIfU/VFbklHsOUBWOPKT984s1j+1F04PW7tgYPmDlEDJTtwtQKCXYZuxIi+gVaIYpC6Y=
